package com.github.marschall.ishimura;

/**
 * A wrapper interface
 */
public interface UnsafeWrapper {
  public Object allocateInstance(Class arg0) throws InstantiationException;
  public void copyMemory(long arg0, long arg1, long arg2);
  public void copyMemory(Object arg0, long arg1, Object arg2, long arg3, long arg4);
  public void park(boolean arg0, long arg1);
  public void unpark(Object arg0);
  public void loadFence();
  public void storeFence();
  public void fullFence();
  public Object getObject(Object arg0, long arg1);
  public Object getObject(Object arg0, int arg1);
  public void putObject(Object arg0, long arg1, Object arg2);
  public void putObject(Object arg0, int arg1, Object arg2);
  public boolean getBoolean(Object arg0, int arg1);
  public boolean getBoolean(Object arg0, long arg1);
  public void putBoolean(Object arg0, int arg1, boolean arg2);
  public void putBoolean(Object arg0, long arg1, boolean arg2);
  public byte getByte(long arg0);
  public byte getByte(Object arg0, long arg1);
  public byte getByte(Object arg0, int arg1);
  public void putByte(long arg0, byte arg1);
  public void putByte(Object arg0, int arg1, byte arg2);
  public void putByte(Object arg0, long arg1, byte arg2);
  public short getShort(Object arg0, int arg1);
  public short getShort(long arg0);
  public short getShort(Object arg0, long arg1);
  public void putShort(Object arg0, int arg1, short arg2);
  public void putShort(long arg0, short arg1);
  public void putShort(Object arg0, long arg1, short arg2);
  public char getChar(long arg0);
  public char getChar(Object arg0, long arg1);
  public char getChar(Object arg0, int arg1);
  public void putChar(long arg0, char arg1);
  public void putChar(Object arg0, long arg1, char arg2);
  public void putChar(Object arg0, int arg1, char arg2);
  public int getInt(Object arg0, long arg1);
  public int getInt(Object arg0, int arg1);
  public int getInt(long arg0);
  public void putInt(long arg0, int arg1);
  public void putInt(Object arg0, int arg1, int arg2);
  public void putInt(Object arg0, long arg1, int arg2);
  public long getLong(Object arg0, int arg1);
  public long getLong(long arg0);
  public long getLong(Object arg0, long arg1);
  public void putLong(long arg0, long arg1);
  public void putLong(Object arg0, long arg1, long arg2);
  public void putLong(Object arg0, int arg1, long arg2);
  public float getFloat(Object arg0, long arg1);
  public float getFloat(long arg0);
  public float getFloat(Object arg0, int arg1);
  public void putFloat(Object arg0, long arg1, float arg2);
  public void putFloat(long arg0, float arg1);
  public void putFloat(Object arg0, int arg1, float arg2);
  public double getDouble(Object arg0, long arg1);
  public double getDouble(Object arg0, int arg1);
  public double getDouble(long arg0);
  public void putDouble(Object arg0, int arg1, double arg2);
  public void putDouble(long arg0, double arg1);
  public void putDouble(Object arg0, long arg1, double arg2);
  public Object getObjectVolatile(Object arg0, long arg1);
  public void putObjectVolatile(Object arg0, long arg1, Object arg2);
  public boolean getBooleanVolatile(Object arg0, long arg1);
  public void putBooleanVolatile(Object arg0, long arg1, boolean arg2);
  public byte getByteVolatile(Object arg0, long arg1);
  public void putByteVolatile(Object arg0, long arg1, byte arg2);
  public short getShortVolatile(Object arg0, long arg1);
  public void putShortVolatile(Object arg0, long arg1, short arg2);
  public char getCharVolatile(Object arg0, long arg1);
  public void putCharVolatile(Object arg0, long arg1, char arg2);
  public int getIntVolatile(Object arg0, long arg1);
  public void putIntVolatile(Object arg0, long arg1, int arg2);
  public long getLongVolatile(Object arg0, long arg1);
  public void putLongVolatile(Object arg0, long arg1, long arg2);
  public float getFloatVolatile(Object arg0, long arg1);
  public void putFloatVolatile(Object arg0, long arg1, float arg2);
  public double getDoubleVolatile(Object arg0, long arg1);
  public void putDoubleVolatile(Object arg0, long arg1, double arg2);
  public long getAddress(long arg0);
  public void putAddress(long arg0, long arg1);
  public boolean compareAndSwapObject(Object arg0, long arg1, Object arg2, Object arg3);
  public boolean compareAndSwapLong(Object arg0, long arg1, long arg2, long arg3);
  public boolean compareAndSwapInt(Object arg0, long arg1, int arg2, int arg3);
  public void putOrderedObject(Object arg0, long arg1, Object arg2);
  public void putOrderedLong(Object arg0, long arg1, long arg2);
  public void putOrderedInt(Object arg0, long arg1, int arg2);
  public int getAndAddInt(Object arg0, long arg1, int arg2);
  public long getAndAddLong(Object arg0, long arg1, long arg2);
  public int getAndSetInt(Object arg0, long arg1, int arg2);
  public long getAndSetLong(Object arg0, long arg1, long arg2);
  public Object getAndSetObject(Object arg0, long arg1, Object arg2);
  public void throwException(Throwable arg0);
  public Class defineClass(String arg0, byte[] arg1, int arg2, int arg3, ClassLoader arg4, java.security.ProtectionDomain arg5);
  public Object staticFieldBase(java.lang.reflect.Field arg0);
  public Object staticFieldBase(Class arg0);
  public int fieldOffset(java.lang.reflect.Field arg0);
  public long staticFieldOffset(java.lang.reflect.Field arg0);
  public long objectFieldOffset(java.lang.reflect.Field arg0);
  public boolean shouldBeInitialized(Class arg0);
  public void ensureClassInitialized(Class arg0);
  public long allocateMemory(long arg0);
  public long reallocateMemory(long arg0, long arg1);
  public void setMemory(long arg0, long arg1, byte arg2);
  public void setMemory(Object arg0, long arg1, long arg2, byte arg3);
  public void freeMemory(long arg0);
  public int arrayBaseOffset(Class arg0);
  public int arrayIndexScale(Class arg0);
  public int addressSize();
  public int pageSize();
  public Class defineAnonymousClass(Class arg0, byte[] arg1, Object[] arg2);
  public void monitorEnter(Object arg0);
  public void monitorExit(Object arg0);
  public boolean tryMonitorEnter(Object arg0);
  public int getLoadAverage(double[] arg0, int arg1);
}
